### ISSUE TITLE
Incorrect sync between `Transform::rotation` and `Rotation` 2

### ISSUE THREAD

**Issue by Shatur** [Jondolf/avian#522]
The previously discovered desync from #516 has been fixed in #520. However, I found another way to cause a desync on the latest `main`.
Here is a minimal example to reproduce:

[collider_bug.zip](https://github.com/user-attachments/files/17099971/collider_bug.zip)

Copy it to `crates/avian3d/examples` and run it with `cargo run --example collider_bug`.
When the window opens, just press "Space" a few times to rotate the object, and you will notice the desync:

![Screenshot_20240923_181803](https://github.com/user-attachments/assets/01b4bb13-fa9f-4466-b245-b897db26fbef)

**Comment by coreh** [comment]
I believe I might be hitting a more extreme version of this:

[CW: Videogame Violence]

https://github.com/user-attachments/assets/2199393a-27ce-4b58-b302-fac6b36e09c2

See #573

**Comment by Jondolf** [comment]
This should be fixed by #575. @coreh let me know if it also happens to fix the issue you're seeing here?

**Comment by coreh** [comment]
@Jondolf Just updated to the release version of 0.2.0. The upside down enemies bug is indeed fixed #575, however, the floating point precision/quaternion normalization crash from #573 is still present, so they were not the same. Manually patching [this section](https://github.com/Jondolf/avian/blob/6bfa89e33007b49b54837cd25934cc845d8c09e1/src/sync/mod.rs#L275-L278) adding a call to `.normalize()` fixes the crash.
